FROM strapi/base

RUN yarn global add strapi

RUN mkdir /srv/app && chown 1000:1000 -R /srv/app

WORKDIR /srv/app

VOLUME /srv/app

COPY . .

RUN yarn install

ENV NODE_ENV production

RUN yarn build

EXPOSE 1337

RUN cd /srv/app

CMD ["strapi", "start"]
